FROM node:22-alpine

RUN apk add --no-cache \
    vips-dev \
    python3 \
    make \
    g++ \
    cairo-dev \
    pango-dev \
    pixman-dev \
    curl

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ENV NODE_ENV=development PORT=3000

EXPOSE 3000 9229

CMD ["node", "--watch", "--inspect=0.0.0.0:9229", "server.js"]
